_target_: logger_utils.create_composite_logger
loggers:
  - _target_: lightning.pytorch.loggers.TensorBoardLogger
    name: lightning_logs
    version: null
    sub_dir: ""
    log_graph: false
  - _target_: lightning.pytorch.loggers.CSVLogger
    name: csv_logs
    version: null
    flush_logs_every_n_steps: 100
